// ============================================================
// KSL COURSE OUTLINE TOPICS - Per ATP Unit (2026/2027)
// Compact topic mapping for grounding AI quiz generation
// ============================================================

export const COURSE_OUTLINE_TOPICS: Record<string, string[]> = {
  'atp-100': [
    'Overview of Civil Litigation & Taking Instructions',
    'Courts and Jurisdiction (High Court, Magistrates Courts, Small Claims Court, Tribunals)',
    'Overriding Objective (Section 1A & 1B CPA, Order 11A)',
    'Parties to a Suit (joinder, representative suits, minors, persons of unsound mind)',
    'Commencement of Suits (plaints, petitions, originating summons, constitutional petitions)',
    'Interlocutory Applications (injunctions, security for costs, summary judgment, striking out)',
    'Pre-Trial (discovery, interrogatories, admissions, mediation, case management)',
    'Hearing (witness examination, documentary evidence, submissions, assessors)',
    'Rulings, Orders and Judgments (consent orders, ex parte, default judgment)',
    'Remedies (damages, injunctions, declarations, specific performance, account)',
    'Execution of Decrees (attachment, garnishee orders, committal, receiver)',
    'Review of Judgments and Orders',
    'Appeals (Court of Appeal procedures, Supreme Court, second appeals)',
    'Judicial Review (certiorari, prohibition, mandamus, quo warranto)',
    'Constitutional Litigation (Bill of Rights petitions, locus standi, public interest)',
    'Costs (party-and-party, advocate-and-client, taxation)',
    'Tribunals (Employment & Labour, Environment & Land, Tax Appeals)',
  ],

  'atp-101': [
    'Introduction to Criminal Litigation & Classification of Offences',
    'Jurisdiction and Criminal Courts (Magistrates, High Court, Court of Appeal, Supreme Court)',
    'Arrests (citizen\'s arrest, police arrest, warrants of arrest, rights on arrest)',
    'Identification Parades (procedure, admissibility, dock identification)',
    'Police File Preparation & Criminal Investigations',
    'Complaints, Charge Sheets and Criminal Informations',
    'Plea and Plea Bargaining (procedure, guidelines, victim participation)',
    'Bail and Bond (constitutional right, conditions, cash bail, bond terms)',
    'Pre-Trial Conferencing and Case Management in Criminal Cases',
    'Criminal Trial Process (prosecution case, defence case, submissions, judgment, sentencing)',
    'Appellate Jurisdiction in Criminal Matters (first appeals, second appeals)',
    'Specialized Prosecutors (ODPP, EACC, KRA)',
    'Private Prosecutions (requirements, role of DPP)',
    'Inquests (procedure, findings, reopening)',
    'Extradition (procedures, treaties, conditions)',
    'Miscellaneous Criminal Applications (review, revision, pardon)',
    'Habeas Corpus (Art 51, procedure, grounds)',
    'Judicial Review in Criminal Matters',
    'Special Courts (Court Martial, Kadhi\'s Courts)',
  ],

  'atp-102': [
    'Introduction & Historical Background of Succession Law in Kenya',
    'Legal Framework for Succession (Law of Succession Act, relationship to other laws)',
    'Property Exemptions from Succession (trust property, joint tenancy, insurance)',
    'Testate Succession: Wills and Codicils (formalities, types, capacity)',
    'Revocation, Alteration and Revival of Wills',
    'Proof of Wills (attestation, conditional/contingent wills)',
    'Objections to Wills and Caveats',
    'Reasonable Provision for Dependants (Section 26, free testation limits)',
    'Intestate Succession (distribution rules, ranking of beneficiaries, partial intestacy)',
    'Protection and Preservation of Estate (caveats, intermeddling)',
    'Jurisdiction in Succession Matters (High Court, Magistrates Courts)',
    'Petition for Grant of Probate / Letters of Administration',
    'Objections to Grants and Citation Proceedings',
    'Confirmation of Grants (procedure, distribution schedule)',
    'Revocation and Annulment of Grants (grounds, procedure)',
    'Limited Grants (ad litem, ad colligenda bona, durante minore)',
    'Foreign Grants and Resealing',
    'Personal Representatives (duties, powers, liabilities, removal)',
    'Estate Accounts and Distribution of Assets',
  ],

  'atp-103': [
    'Legal Writing: Plain English Principles in Legal Writing',
    'Legal Writing: Effective Paragraphing and Sentence Structure',
    'Legal Writing: Transitions, Coherence and Flow',
    'Legal Writing: Legal Research Methodology and Citation',
    'Legal Writing: Case Briefs and Legal Memoranda',
    'Legal Drafting: Demand Letters and Correspondence',
    'Legal Drafting: Legal Opinions (structure, analysis, advice)',
    'Legal Drafting: Contracts (terms, conditions, boilerplate clauses)',
    'Legal Drafting: Affidavits and Statutory Declarations',
    'Legal Drafting: Deed Polls and Conveyancing Instruments',
    'Legislative Drafting: Structure of Bills (long title, short title, preamble, parts)',
    'Legislative Drafting: The Legislative Sentence (provisos, exceptions, definitions)',
    'Legislative Drafting: Amending Legislation (textual vs non-textual amendments)',
    'Legislative Drafting: Penal Provisions and Penalty Clauses',
    'Legislative Drafting: Delegated/Subsidiary Legislation (regulations, rules, orders)',
  ],

  'atp-104': [
    'Introduction to Trial Advocacy & The Advocates\' Role',
    'Qualities of a Good Trial Lawyer (preparation, persuasion, ethics)',
    'Ethical Duties in Advocacy (duty to court, candour, not misleading)',
    'Conflict of Interest in Litigation Contexts',
    'Court Etiquette, Decorum and Professional Conduct',
    'Dimensions, Rules and Psychology of Advocacy',
    'Pre-Trial Preparation (case theory, theme, witness interviews, document review)',
    'Opening Statements (structure, do\'s and don\'ts, primacy effect)',
    'Examination-in-Chief (open questions, refreshing memory, hostile witnesses)',
    'Cross-Examination (techniques, leading questions, impeachment, prior inconsistent statements)',
    'Re-Examination (rehabilitation, clarification, limits)',
    'Closing Arguments and Final Submissions',
    'Objections (hearsay, relevance, leading questions, speculation, best evidence)',
    'Skeleton Arguments and Written Submissions (structure, authorities)',
    'Appellate Advocacy (grounds of appeal, leave, oral submissions)',
    'Contempt of Court (civil vs criminal, inherent power, procedure)',
    'Alternative Dispute Resolution (mediation, arbitration, negotiation, traditional methods)',
  ],

  'atp-105': [
    'Introduction to Ethics and Morality in Legal Practice',
    'Law as a Profession in Kenya (entry requirements, admission, pupillage)',
    'Role and Functions of the Law Society of Kenya',
    'SOPPEC Standards Overview (Standards 1-12 of Professional Conduct)',
    'Fidelity to Law and Its Limits (rule of law, civil disobedience)',
    'Role of the Lawyer in Society (officer of the court, social justice)',
    'Confidentiality and Legal Professional Privilege (scope, exceptions, waiver)',
    'Professional Undertakings (nature, obligation, breach consequences)',
    'Conflict of Interest (concurrent conflicts, successive clients, imputed conflicts)',
    'Judicial Recusal and Bias (actual bias, apparent bias, tests)',
    'Competence, Diligence and Professional Negligence (standard of care, liability)',
    'Professional Fees, Retainers and Remuneration of Advocates',
    'Taxation of Bills of Costs (principles, instruction fees, disbursements)',
    'Fiduciary Duty over Client Funds (champerty, trust, misappropriation, accounts)',
    'Advocate\'s Lien (retaining lien, statutory lien, enforcement)',
    'Touting, Marketing and Advertising Rules for Advocates',
    'Requirement for Practicing Certificate and CPDs',
    'Advocates Disciplinary Process (misconduct, complaints, tribunal)',
    'AI, Techno-Ethics and Legal Professionals',
    'Anti-Money Laundering Obligations for Lawyers',
    'Social Media Conduct and Outside Interests',
    'Contempt of Court in the Ethics Context',
    'Law as a Business (firm establishment, types, multi-disciplinary practice)',
  ],

  'atp-106': [
    'Introduction to Office Administration & Management in Law Firms',
    'Front Office Services (location, layout, customer service, reception)',
    'Office Standards, Policies and Procedures',
    'ICT in Legal Practice (automation, document management, cybersecurity)',
    'Record Management and Filing Systems',
    'Supply Chain Management and Procurement in Law Firms',
    'Safety, Security and Disaster Management',
    'Discrimination and Sexual Harassment at the Workplace',
    'Human Resource Planning and Management (strategic HRM)',
    'Job Analysis and Design in Legal Practice',
    'Recruitment and Selection of Legal Staff',
    'Placement, Induction and Socialization',
    'Training, Development and Career Management',
    'Internal Mobility and Separation (promotion, transfer, demotion, termination)',
    'Conceptual Framework of Accounting (principles, IFRS, concepts)',
    'Book Keeping and End Year Adjustments (trial balance, errors)',
    'Bank Reconciliation Statements',
    'Preparation of Final Accounts (income statement, balance sheet)',
    'Partnership Accounts',
    'Advocates Accounts (client accounts, income accounts, cashbook)',
    'Cash Flow Statements Analysis (direct and indirect methods)',
    'Cost Accounting and Budgeting',
  ],

  'atp-107': [
    'Introduction to Conveyancing (definition, nature, scope, historical evolution)',
    'Historical and Legal Framework (UK 1535-1925, Kenya pre/post colonization)',
    'Land Tenure, Estates and Interests (freehold, leasehold, public/private/community land)',
    'Pre-Contract Stage (client interview, instructions, due diligence, searches)',
    'Contracts for Sale of Land (agreement for sale, LSK conditions, special conditions)',
    'Roles of Advocates in Conveyancing (vendor/purchaser/financier advocates)',
    'Other Dispositions (auction, off-plan, sectional properties, community land sales)',
    'Transfer and Registration (voluntary transfers, forms, attestation, execution)',
    'Interests Transferred (freehold, leasehold, charges, assignments)',
    'Sub-leases and Sectional Properties (management corporations, registration)',
    'Completion Documents (Land Control Board consent, spousal consent, clearances)',
    'Transmissions / Involuntary Transfers (death, court attachment, vesting, adverse possession)',
    'Leases and Tenancies (types, registration, implied conditions, covenants)',
    'Controlled Tenancies and Rent Acts (Shops/Hotels Act, Rent Restriction Act)',
    'Determination of Leases (forfeiture, distress, remedies)',
    'Charges and Mortgages (types, priority, tacking, form and content)',
    'Remedies of Chargee and Chargor (power of sale, redemption, receiver)',
    'Easements, Profits, Restrictive Covenants and Wayleaves',
    'Cautions, Inhibitions and Restrictions (lodging, removal, effects)',
    'Taxation in Conveyancing (stamp duty, capital gains tax, VAT, rates)',
    'Compulsory Acquisition and Allocation of Land',
    'Land Planning, Change of User, Extension and Renewal of Leases',
    'Institutional Framework (Ministry of Lands, NLC, NEMA, County Governments)',
    'Contemporary Issues and Reforms (electronic registration, NLIMS, Ardhi Sasa)',
  ],

  'atp-108': [
    'Companies: Formation, Types and Incorporation (private, public, foreign)',
    'Companies: Statutory Compliance, Returns and Officers',
    'Companies: Resolutions, Meetings and Share Capital',
    'Companies: Charges, Registration and Beneficial Ownership',
    'Partnerships: Forms, Incorporation and Compliance (general, LLP)',
    'Partnerships: Partnership Deed, Property and Dissolution',
    'Mergers, Acquisitions and Take-Overs (framework, due diligence, term sheets)',
    'Mergers: Notification Thresholds, Disclosure (Kenya and COMESA)',
    'Insolvency: Legal Principles and Procedures (bankruptcy, administration, liquidation)',
    'Insolvency: Rights of Creditors and Debtors, Role of Practitioners',
    'Financial Services and Payment Systems (electronic payments, digital currencies)',
    'Commercial Agreements (key elements, negotiation, drafting, enforcement, remedies)',
    'Movable Property Security Rights (creation, perfection, enforcement, collateral registry)',
    'Tax Procedures in Commercial Transactions (income tax, VAT, compliance, disputes)',
  ],
};
